version: "3.3"
services:
  db:
    restart: always
    image: elestio/postgres:15
    container_name: db
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']    
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:8290:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=mastodon_production

  redis:
    restart: always
    image: elestio/redis:7.0
    container_name: redis
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./storage/redis:/data

  opensearch:
    image: opensearchproject/opensearch:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
      - "bootstrap.memory_lock=true"
      - "cluster.name=opensearch-mastodon"
      - "discovery.type=single-node"
      - "thread_pool.write.queue_size=1000"
      - "node.name=opensearch"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./storage/opensearch:/usr/share/opensearch/data
    ports:
      - 172.17.0.1:9280:9200

  web:
    image: ghcr.io/mastodon/mastodon:${SOFTWARE_VERSION_TAG}
    restart: always
    env_file: ./.env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - "172.17.0.1:7834:3000"
    depends_on:
      - db
      - redis
      - opensearch
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    image: ghcr.io/mastodon/mastodon:${SOFTWARE_VERSION_TAG}
    restart: always
    env_file: ./.env
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - "172.17.0.1:8834:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    image: ghcr.io/mastodon/mastodon:${SOFTWARE_VERSION_TAG}
    restart: always
    env_file: ./.env
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network  
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]  

  pgadmin4:
    image: dpage/pgadmin4:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:8367:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - 172.17.0.1:6835:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
networks:
  external_network:
  internal_network:
    internal: true
